name: restore-opam-cache
runs:
  using: composite
  steps:
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-opam-cache-{{ arch }}-{{ checksum ".circleci/opamcachebreaker" }}
      path: UPDATE_ME
      restore-keys: v1-opam-cache-{{ arch }}-{{ checksum ".circleci/opamcachebreaker" }}